menu:
  Archives: /archives
  Projects: /projects
  About: /about

widgets:
- search
- category
- tag
- twitter

excerpt_link: read more

# not currently working
#twitter:
  #username: mervinej
  #show_replies: true
  #tweet_count: 5

# or
twitter_id: mervinej

facebook_id: mervinej
linkedin_id: mervinej
github_id: jmervine

addthis:
  enable: true
  pubid: ra-520c00d223718563
  twitter: true
  facebook: true

#fancybox: true

google_analytics:
rss:

disqus_shortname: rubyops

keywords: site, wide, default, keywords
